name: Pipeline Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Log into ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        
      - name: Build Docker image and push to ACR
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.AZURE_IMAGE_NAME }}:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.AZURE_IMAGE_NAME }}:latest

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.AZURE_IMAGE_NAME }}:latest
          slot-name: production
      
      - name: Logout
        run: |
          az logout